### ISSUE TITLE
EventDisplayPanel resize behavior

### ISSUE THREAD

**Issue by BrianRistau** [BrianRistau/Efishent#9]
The behavior of the EventDisplayPanel objects is as expected when the application becomes larger horizontally.  However, when the application is scaled back down horizontally, a scrollbar will appear in the EventPanel due to the EventDisplayPanel objects being too large for the frame.

**Comment by Nekonohimitsu** [comment]
Fixed by implementing a ScrollablePanel class in frontend.special
http://stackoverflow.com/questions/15783014/jtextarea-on-jpanel-inside-jscrollpane-does-not-resize-properly
